### PR TITLE
Set alias to 2.0-dev

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open

**Comment by chives** [comment]
:+1:

**Comment by norzechowicz** [comment]
dude, chill.. One request is perfectly fine, no need to spam everybody else each few hours...

**Comment by szymach** [comment]
I could always merge it myself like you do. Looks like we both need our candy exactly when we want it :)

**Comment by norzechowicz** [comment]
No you can't because you are not skilled enough - that's why you need to be patinent ant wait for other ppl to merge your changes.

**Comment by szymach** [comment]
I only did this change because you did not include it in you previous PR. Also [here](https://github.com/fsi-open/admin-positionable-bundle/issues/23) I specifically asked you about this change and you did not respond. I have been quite patient, I think, waiting 11 days.

**Pull request merged**
