### PR TITLE
Added pre and post action events

### LINKED ISSUE #27: Emit events on position change
This could allow for hooking up actions related to position changes.

### PR DESCRIPTION
**Pull request by szymach**
Resolves #27

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by JarekW** [comment]
Do we need information in event about direction of the move (up/down)?

**Comment by szymach** [comment]
I could not think of a good use case for that, so I would say no.

**Comment by szymach** [comment]
@fsi-open

**Pull request merged**
